-- ======================================================================
-- 2_dims.sql — Dimensions (conformed)
-- ======================================================================
WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = GOLD_LAYER;

-- ===============================
-- DIM_DATE (calendar)
-- ===============================
CREATE TABLE DIM_DATE (
  DATE_KEY        NUMBER(8)    PRIMARY KEY, -- YYYYMMDD
  FULL_DATE       DATE         NOT NULL,
  YEAR_NUM        NUMBER(4)    NOT NULL,
  QUARTER_NUM     NUMBER(1)    NOT NULL,
  MONTH_NUM       NUMBER(2)    NOT NULL,
  MONTH_NAME      VARCHAR2(15) NOT NULL,
  DAY_NUM         NUMBER(2)    NOT NULL,
  DAY_NAME        VARCHAR2(15) NOT NULL,
  WEEK_OF_YEAR    NUMBER(2)    NOT NULL,
  IS_WEEKEND      NUMBER(1)    NOT NULL,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UX_DIM_DATE_FULL ON DIM_DATE(FULL_DATE);

-- ===============================
-- DIM_BRANCH
-- ===============================
CREATE TABLE DIM_BRANCH (
  BRANCH_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BRANCH_ID    NUMBER NOT NULL,
  BRANCH_NAME  VARCHAR2(100) NOT NULL,
  CITY         VARCHAR2(100) NOT NULL,
  ADDRESS      VARCHAR2(200),
  PHONE        VARCHAR2(30),
  EMAIL        VARCHAR2(100),
  CREATED_AT   TIMESTAMP,
  IS_ACTIVE    NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS      TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_BRANCH ADD CONSTRAINT UK_DIM_BRANCH_NK UNIQUE (BRANCH_ID);
CREATE INDEX IDX_DIM_BRANCH_CITY ON DIM_BRANCH(CITY);

-- ===============================
-- DIM_MANAGER
-- ===============================
CREATE TABLE DIM_MANAGER (
  MANAGER_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MANAGER_ID    NUMBER NOT NULL,
  MANAGER_CODE  VARCHAR2(20) NOT NULL,
  FIRST_NAME    VARCHAR2(50) NOT NULL,
  LAST_NAME     VARCHAR2(50) NOT NULL,
  EMAIL         VARCHAR2(100) NOT NULL,
  PHONE         VARCHAR2(30),
  ROLE          VARCHAR2(20) NOT NULL,
  BRANCH_ID     NUMBER,
  HIRE_DATE     DATE,
  IS_ACTIVE     NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS       TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_MANAGER ADD CONSTRAINT UK_DIM_MANAGER_NK UNIQUE (MANAGER_ID);
CREATE INDEX IDX_DIM_MANAGER_BRANCH ON DIM_MANAGER(BRANCH_ID);
CREATE INDEX IDX_DIM_MANAGER_ROLE   ON DIM_MANAGER(ROLE);

-- ===============================
-- DIM_CATEGORY
-- ===============================
CREATE TABLE DIM_CATEGORY (
  CATEGORY_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATEGORY_ID    NUMBER NOT NULL,
  CATEGORY_NAME  VARCHAR2(60) NOT NULL,
  DESCRIPTION    VARCHAR2(400),
  CREATED_AT     TIMESTAMP,
  IS_ACTIVE      NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS        TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_CATEGORY ADD CONSTRAINT UK_DIM_CATEGORY_NK UNIQUE (CATEGORY_ID);
CREATE INDEX IDX_DIM_CATEGORY_NAME ON DIM_CATEGORY(CATEGORY_NAME);

-- ===============================
-- DIM_CAR
-- ===============================
CREATE TABLE DIM_CAR (
  CAR_KEY        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CAR_ID         NUMBER NOT NULL,
  CATEGORY_ID    NUMBER NOT NULL,
  DEVICE_ID      NUMBER,
  VIN            VARCHAR2(30) NOT NULL,
  LICENSE_PLATE  VARCHAR2(20) NOT NULL,
  MAKE           VARCHAR2(60) NOT NULL,
  MODEL          VARCHAR2(60) NOT NULL,
  MODEL_YEAR     NUMBER(4),
  COLOR          VARCHAR2(40),
  IMAGE_URL      VARCHAR2(500),
  ODOMETER_KM    NUMBER(10,0),
  STATUS         VARCHAR2(20),
  BRANCH_ID      NUMBER,
  CREATED_AT     TIMESTAMP,
  IS_ACTIVE      NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS        TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_CAR ADD CONSTRAINT UK_DIM_CAR_NK UNIQUE (CAR_ID);
CREATE INDEX IDX_DIM_CAR_BRANCH ON DIM_CAR(BRANCH_ID);
CREATE INDEX IDX_DIM_CAR_CAT    ON DIM_CAR(CATEGORY_ID);
CREATE INDEX IDX_DIM_CAR_PLATE  ON DIM_CAR(LICENSE_PLATE);

-- ===============================
-- DIM_CUSTOMER
-- ===============================
CREATE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID        NUMBER NOT NULL,
  BRANCH_ID          NUMBER NOT NULL,
  MANAGER_ID         NUMBER NOT NULL,
  FIRST_NAME         VARCHAR2(80) NOT NULL,
  LAST_NAME          VARCHAR2(80) NOT NULL,
  NATIONAL_ID        VARCHAR2(20) NOT NULL,
  DATE_OF_BIRTH      DATE NOT NULL,
  DRIVER_LICENSE_NO  VARCHAR2(30) NOT NULL,
  EMAIL              VARCHAR2(160),
  PHONE              VARCHAR2(40),
  CREATED_AT         TIMESTAMP,
  IS_ACTIVE          NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS            TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_CUSTOMER ADD CONSTRAINT UK_DIM_CUSTOMER_NK UNIQUE (CUSTOMER_ID);
CREATE INDEX IDX_DIM_CUSTOMER_BRANCH ON DIM_CUSTOMER(BRANCH_ID);
CREATE INDEX IDX_DIM_CUSTOMER_NAME   ON DIM_CUSTOMER(LAST_NAME, FIRST_NAME);

-- ===============================
-- DIM_DEVICE
-- ===============================
CREATE TABLE DIM_DEVICE (
  DEVICE_KEY       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DEVICE_ID        NUMBER NOT NULL,
  DEVICE_CODE      VARCHAR2(40) NOT NULL,
  DEVICE_IMEI      VARCHAR2(20),
  FIRMWARE_VERSION VARCHAR2(40),
  STATUS           VARCHAR2(20),
  BRANCH_ID        NUMBER,
  ACTIVATED_AT     TIMESTAMP,
  LAST_SEEN_AT     TIMESTAMP,
  CREATED_AT       TIMESTAMP,
  IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS          TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_DEVICE ADD CONSTRAINT UK_DIM_DEVICE_NK UNIQUE (DEVICE_ID);
CREATE INDEX IDX_DIM_DEVICE_BRANCH ON DIM_DEVICE(BRANCH_ID);
CREATE INDEX IDX_DIM_DEVICE_STATUS ON DIM_DEVICE(STATUS);

COMMIT;
PROMPT [OK] Dimensions created
