-- ======================================================================
-- 3_facts.sql — Facts
-- ======================================================================
WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
SET SCAN OFF
ALTER SESSION SET CURRENT_SCHEMA = GOLD_LAYER;

-- ===============================
-- FACT_RENTAL (grain = 1 rental)
-- ===============================
CREATE TABLE FACT_RENTAL (
  RENTAL_KEY       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RENTAL_ID        NUMBER NOT NULL,
  START_DATE_KEY   NUMBER(8) NOT NULL,
  END_DATE_KEY     NUMBER(8),
  BRANCH_ID        NUMBER NOT NULL,
  MANAGER_ID       NUMBER NOT NULL,
  CAR_ID           NUMBER NOT NULL,
  CUSTOMER_ID      NUMBER NOT NULL,
  START_AT         TIMESTAMP NOT NULL,
  DUE_AT           TIMESTAMP NOT NULL,
  RETURN_AT        TIMESTAMP,
  STATUS           VARCHAR2(20),
  START_ODOMETER   NUMBER(10,0),
  END_ODOMETER     NUMBER(10,0),
  TOTAL_AMOUNT     NUMBER(12,2),
  CURRENCY         VARCHAR2(3),
  DURATION_HOURS   NUMBER(10,2),
  DISTANCE_KM      NUMBER(12,2),
  CREATED_AT       TIMESTAMP,
  LOAD_TS          TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE FACT_RENTAL ADD CONSTRAINT UK_FACT_RENTAL_NK UNIQUE (RENTAL_ID);
CREATE INDEX IDX_FACT_RENTAL_STARTKEY ON FACT_RENTAL(START_DATE_KEY);
CREATE INDEX IDX_FACT_RENTAL_BRANCH   ON FACT_RENTAL(BRANCH_ID);
CREATE INDEX IDX_FACT_RENTAL_CAR      ON FACT_RENTAL(CAR_ID);
CREATE INDEX IDX_FACT_RENTAL_MGR      ON FACT_RENTAL(MANAGER_ID);
CREATE INDEX IDX_FACT_RENTAL_STATUS   ON FACT_RENTAL(STATUS);

-- ===============================
-- FACT_IOT_ALERT (grain = 1 alert)
-- ===============================
CREATE TABLE FACT_IOT_ALERT (
  ALERT_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ALERT_ID    NUMBER NOT NULL,
  DATE_KEY    NUMBER(8) NOT NULL,
  BRANCH_ID   NUMBER,
  STATUS      VARCHAR2(20),
  CREATED_AT  TIMESTAMP,
  LOAD_TS     TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE FACT_IOT_ALERT ADD CONSTRAINT UK_FACT_ALERT_NK UNIQUE (ALERT_ID);
CREATE INDEX IDX_FACT_ALERT_DATE   ON FACT_IOT_ALERT(DATE_KEY);
CREATE INDEX IDX_FACT_ALERT_BRANCH ON FACT_IOT_ALERT(BRANCH_ID);
CREATE INDEX IDX_FACT_ALERT_STATUS ON FACT_IOT_ALERT(STATUS);

-- ===============================
-- FACT_TELEMETRY_DAILY (grain = CAR_ID + DATE_KEY)
-- ===============================
CREATE TABLE FACT_TELEMETRY_DAILY (
  TELEMETRY_DAY_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATE_KEY          NUMBER(8) NOT NULL,
  BRANCH_ID         NUMBER,
  CAR_ID            NUMBER NOT NULL,
  DEVICE_ID         NUMBER,
  POINTS_CNT        NUMBER,
  AVG_SPEED_KMH     NUMBER(10,2),
  MAX_SPEED_KMH     NUMBER(10,2),
  MIN_FUEL_PCT      NUMBER(10,2),
  END_FUEL_PCT      NUMBER(10,2),
  MAX_ENGINE_TEMP_C NUMBER(10,2),
  HARSH_BRAKE_CNT   NUMBER,
  HARSH_ACCEL_CNT   NUMBER,
  OVERHEAT_CNT      NUMBER,
  LOAD_TS           TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX UX_FACT_TELEM_DAILY ON FACT_TELEMETRY_DAILY(DATE_KEY, CAR_ID);
CREATE INDEX IDX_FACT_TELEM_BRANCH     ON FACT_TELEMETRY_DAILY(BRANCH_ID);

-- ===============================
-- FACT_CAR_STATUS_SNAP_DAILY (grain = CAR_ID + DATE_KEY)
-- ===============================
CREATE TABLE FACT_CAR_STATUS_SNAP_DAILY (
  SNAP_KEY     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATE_KEY     NUMBER(8) NOT NULL,
  BRANCH_ID    NUMBER,
  CAR_ID       NUMBER NOT NULL,
  STATUS       VARCHAR2(20),
  ODOMETER_KM  NUMBER(10,0),
  DEVICE_ID    NUMBER,
  LOAD_TS      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX UX_FACT_CAR_SNAP ON FACT_CAR_STATUS_SNAP_DAILY(DATE_KEY, CAR_ID);
CREATE INDEX IDX_FACT_CAR_SNAP_BRANCH ON FACT_CAR_STATUS_SNAP_DAILY(BRANCH_ID);
CREATE INDEX IDX_FACT_CAR_SNAP_STATUS ON FACT_CAR_STATUS_SNAP_DAILY(STATUS);

COMMIT;
PROMPT [OK] Facts created