-- ======================================================================
-- 4_pkg_load.sql — Package de chargement GOLD (MERGE/INSERT)
-- ======================================================================
WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
SET SCAN OFF
ALTER SESSION SET CURRENT_SCHEMA = GOLD_LAYER;

CREATE OR REPLACE PACKAGE PKG_GOLD_LOAD AS
  PROCEDURE LOAD_DIM_DATE(p_start_date DATE, p_end_date DATE);
  PROCEDURE LOAD_DIMS;
  PROCEDURE LOAD_FACT_RENTAL;
  PROCEDURE LOAD_FACT_ALERTS;
  PROCEDURE LOAD_FACT_TELEMETRY_DAILY;
  PROCEDURE LOAD_FACT_CAR_SNAP_DAILY;
  PROCEDURE LOAD_ALL;
END PKG_GOLD_LOAD;
/
SHOW ERRORS

CREATE OR REPLACE PACKAGE BODY PKG_GOLD_LOAD AS

  PROCEDURE LOAD_DIM_DATE(p_start_date DATE, p_end_date DATE) IS
    d DATE := TRUNC(p_start_date);
  BEGIN
    WHILE d <= TRUNC(p_end_date) LOOP
      MERGE INTO DIM_DATE t
      USING (
        SELECT
          TO_NUMBER(TO_CHAR(d,'YYYYMMDD')) AS DATE_KEY,
          d AS FULL_DATE,
          TO_NUMBER(TO_CHAR(d,'YYYY')) AS YEAR_NUM,
          TO_NUMBER(TO_CHAR(d,'Q')) AS QUARTER_NUM,
          TO_NUMBER(TO_CHAR(d,'MM')) AS MONTH_NUM,
          TO_CHAR(d,'Month') AS MONTH_NAME,
          TO_NUMBER(TO_CHAR(d,'DD')) AS DAY_NUM,
          TO_CHAR(d,'Day') AS DAY_NAME,
          TO_NUMBER(TO_CHAR(d,'IW')) AS WEEK_OF_YEAR,
          CASE WHEN TO_CHAR(d,'D') IN ('1','7') THEN 1 ELSE 0 END AS IS_WEEKEND
        FROM dual
      ) s
      ON (t.DATE_KEY = s.DATE_KEY)
      WHEN MATCHED THEN UPDATE SET
        t.FULL_DATE    = s.FULL_DATE,
        t.YEAR_NUM     = s.YEAR_NUM,
        t.QUARTER_NUM  = s.QUARTER_NUM,
        t.MONTH_NUM    = s.MONTH_NUM,
        t.MONTH_NAME   = TRIM(s.MONTH_NAME),
        t.DAY_NUM      = s.DAY_NUM,
        t.DAY_NAME     = TRIM(s.DAY_NAME),
        t.WEEK_OF_YEAR = s.WEEK_OF_YEAR,
        t.IS_WEEKEND   = s.IS_WEEKEND
      WHEN NOT MATCHED THEN INSERT (
        DATE_KEY, FULL_DATE, YEAR_NUM, QUARTER_NUM, MONTH_NUM, MONTH_NAME,
        DAY_NUM, DAY_NAME, WEEK_OF_YEAR, IS_WEEKEND
      ) VALUES (
        s.DATE_KEY, s.FULL_DATE, s.YEAR_NUM, s.QUARTER_NUM, s.MONTH_NUM, TRIM(s.MONTH_NAME),
        s.DAY_NUM, TRIM(s.DAY_NAME), s.WEEK_OF_YEAR, s.IS_WEEKEND
      );

      d := d + 1;
    END LOOP;
    COMMIT;
  END;

  PROCEDURE LOAD_DIMS IS
  BEGIN
    -- BRANCH
    MERGE INTO DIM_BRANCH t
    USING (
      SELECT BRANCH_ID, BRANCH_NAME, CITY, ADDRESS, PHONE, EMAIL, CREATED_AT
      FROM RAW_LAYER.BRANCHES
    ) s
    ON (t.BRANCH_ID = s.BRANCH_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_NAME = s.BRANCH_NAME,
      t.CITY        = s.CITY,
      t.ADDRESS     = s.ADDRESS,
      t.PHONE       = s.PHONE,
      t.EMAIL       = s.EMAIL,
      t.CREATED_AT  = s.CREATED_AT,
      t.IS_ACTIVE   = 1,
      t.LOAD_TS     = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      BRANCH_ID, BRANCH_NAME, CITY, ADDRESS, PHONE, EMAIL, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.BRANCH_ID, s.BRANCH_NAME, s.CITY, s.ADDRESS, s.PHONE, s.EMAIL, s.CREATED_AT, 1
    );

    -- MANAGER
    MERGE INTO DIM_MANAGER t
    USING (
      SELECT MANAGER_ID, MANAGER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ROLE, BRANCH_ID, HIRE_DATE
      FROM RAW_LAYER.MANAGERS
    ) s
    ON (t.MANAGER_ID = s.MANAGER_ID)
    WHEN MATCHED THEN UPDATE SET
      t.MANAGER_CODE = s.MANAGER_CODE,
      t.FIRST_NAME   = s.FIRST_NAME,
      t.LAST_NAME    = s.LAST_NAME,
      t.EMAIL        = s.EMAIL,
      t.PHONE        = s.PHONE,
      t.ROLE         = s.ROLE,
      t.BRANCH_ID    = s.BRANCH_ID,
      t.HIRE_DATE    = s.HIRE_DATE,
      t.IS_ACTIVE    = 1,
      t.LOAD_TS      = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      MANAGER_ID, MANAGER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ROLE, BRANCH_ID, HIRE_DATE, IS_ACTIVE
    ) VALUES (
      s.MANAGER_ID, s.MANAGER_CODE, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PHONE, s.ROLE, s.BRANCH_ID, s.HIRE_DATE, 1
    );

    -- CATEGORY
    MERGE INTO DIM_CATEGORY t
    USING (
      SELECT CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, CREATED_AT
      FROM RAW_LAYER.CAR_CATEGORIES
    ) s
    ON (t.CATEGORY_ID = s.CATEGORY_ID)
    WHEN MATCHED THEN UPDATE SET
      t.CATEGORY_NAME = s.CATEGORY_NAME,
      t.DESCRIPTION   = s.DESCRIPTION,
      t.CREATED_AT    = s.CREATED_AT,
      t.IS_ACTIVE     = 1,
      t.LOAD_TS       = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.CATEGORY_ID, s.CATEGORY_NAME, s.DESCRIPTION, s.CREATED_AT, 1
    );

    -- CAR
    MERGE INTO DIM_CAR t
    USING (
      SELECT CAR_ID, CATEGORY_ID, DEVICE_ID, VIN, LICENSE_PLATE, MAKE, MODEL, MODEL_YEAR, COLOR,
             IMAGE_URL, ODOMETER_KM, STATUS, BRANCH_ID, CREATED_AT
      FROM RAW_LAYER.CARS
    ) s
    ON (t.CAR_ID = s.CAR_ID)
    WHEN MATCHED THEN UPDATE SET
      t.CATEGORY_ID   = s.CATEGORY_ID,
      t.DEVICE_ID     = s.DEVICE_ID,
      t.VIN           = s.VIN,
      t.LICENSE_PLATE = s.LICENSE_PLATE,
      t.MAKE          = s.MAKE,
      t.MODEL         = s.MODEL,
      t.MODEL_YEAR    = s.MODEL_YEAR,
      t.COLOR         = s.COLOR,
      t.IMAGE_URL     = s.IMAGE_URL,
      t.ODOMETER_KM   = s.ODOMETER_KM,
      t.STATUS        = s.STATUS,
      t.BRANCH_ID     = s.BRANCH_ID,
      t.CREATED_AT    = s.CREATED_AT,
      t.IS_ACTIVE     = 1,
      t.LOAD_TS       = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      CAR_ID, CATEGORY_ID, DEVICE_ID, VIN, LICENSE_PLATE, MAKE, MODEL, MODEL_YEAR, COLOR,
      IMAGE_URL, ODOMETER_KM, STATUS, BRANCH_ID, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.CAR_ID, s.CATEGORY_ID, s.DEVICE_ID, s.VIN, s.LICENSE_PLATE, s.MAKE, s.MODEL, s.MODEL_YEAR, s.COLOR,
      s.IMAGE_URL, s.ODOMETER_KM, s.STATUS, s.BRANCH_ID, s.CREATED_AT, 1
    );

    -- CUSTOMER
    MERGE INTO DIM_CUSTOMER t
    USING (
      SELECT CUSTOMER_ID, BRANCH_ID, MANAGER_ID, FIRST_NAME, LAST_NAME, NATIONAL_ID, DATE_OF_BIRTH,
             DRIVER_LICENSE_NO, EMAIL, PHONE, CREATED_AT
      FROM RAW_LAYER.CUSTOMERS
    ) s
    ON (t.CUSTOMER_ID = s.CUSTOMER_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_ID        = s.BRANCH_ID,
      t.MANAGER_ID       = s.MANAGER_ID,
      t.FIRST_NAME       = s.FIRST_NAME,
      t.LAST_NAME        = s.LAST_NAME,
      t.NATIONAL_ID      = s.NATIONAL_ID,
      t.DATE_OF_BIRTH    = s.DATE_OF_BIRTH,
      t.DRIVER_LICENSE_NO= s.DRIVER_LICENSE_NO,
      t.EMAIL            = s.EMAIL,
      t.PHONE            = s.PHONE,
      t.CREATED_AT       = s.CREATED_AT,
      t.IS_ACTIVE        = 1,
      t.LOAD_TS          = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      CUSTOMER_ID, BRANCH_ID, MANAGER_ID, FIRST_NAME, LAST_NAME, NATIONAL_ID, DATE_OF_BIRTH,
      DRIVER_LICENSE_NO, EMAIL, PHONE, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.CUSTOMER_ID, s.BRANCH_ID, s.MANAGER_ID, s.FIRST_NAME, s.LAST_NAME, s.NATIONAL_ID, s.DATE_OF_BIRTH,
      s.DRIVER_LICENSE_NO, s.EMAIL, s.PHONE, s.CREATED_AT, 1
    );

    -- DEVICE
    MERGE INTO DIM_DEVICE t
    USING (
      SELECT DEVICE_ID, DEVICE_CODE, DEVICE_IMEI, FIRMWARE_VERSION, STATUS, BRANCH_ID,
             ACTIVATED_AT, LAST_SEEN_AT, CREATED_AT
      FROM RAW_LAYER.IOT_DEVICES
    ) s
    ON (t.DEVICE_ID = s.DEVICE_ID)
    WHEN MATCHED THEN UPDATE SET
      t.DEVICE_CODE      = s.DEVICE_CODE,
      t.DEVICE_IMEI      = s.DEVICE_IMEI,
      t.FIRMWARE_VERSION = s.FIRMWARE_VERSION,
      t.STATUS           = s.STATUS,
      t.BRANCH_ID        = s.BRANCH_ID,
      t.ACTIVATED_AT     = s.ACTIVATED_AT,
      t.LAST_SEEN_AT     = s.LAST_SEEN_AT,
      t.CREATED_AT       = s.CREATED_AT,
      t.IS_ACTIVE        = 1,
      t.LOAD_TS          = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      DEVICE_ID, DEVICE_CODE, DEVICE_IMEI, FIRMWARE_VERSION, STATUS, BRANCH_ID,
      ACTIVATED_AT, LAST_SEEN_AT, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.DEVICE_ID, s.DEVICE_CODE, s.DEVICE_IMEI, s.FIRMWARE_VERSION, s.STATUS, s.BRANCH_ID,
      s.ACTIVATED_AT, s.LAST_SEEN_AT, s.CREATED_AT, 1
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_RENTAL IS
  BEGIN
    MERGE INTO FACT_RENTAL t
    USING (
      SELECT
        r.RENTAL_ID,
        TO_NUMBER(TO_CHAR(CAST(r.START_AT AS DATE),'YYYYMMDD')) AS START_DATE_KEY,
        TO_NUMBER(TO_CHAR(CAST(NVL(r.RETURN_AT, r.DUE_AT) AS DATE),'YYYYMMDD')) AS END_DATE_KEY,
        r.BRANCH_ID, r.MANAGER_ID, r.CAR_ID, r.CUSTOMER_ID,
        r.START_AT, r.DUE_AT, r.RETURN_AT, r.STATUS,
        r.START_ODOMETER, r.END_ODOMETER,
        r.TOTAL_AMOUNT, r.CURRENCY,
        ROUND(EXTRACT(DAY FROM (NVL(r.RETURN_AT, r.DUE_AT) - r.START_AT)) * 24 + 
              EXTRACT(HOUR FROM (NVL(r.RETURN_AT, r.DUE_AT) - r.START_AT)) + 
              EXTRACT(MINUTE FROM (NVL(r.RETURN_AT, r.DUE_AT) - r.START_AT)) / 60, 2) AS DURATION_HOURS,
        CASE
          WHEN r.START_ODOMETER IS NOT NULL AND r.END_ODOMETER IS NOT NULL
          THEN ROUND(r.END_ODOMETER - r.START_ODOMETER, 2)
          ELSE NULL
        END AS DISTANCE_KM,
        r.CREATED_AT
      FROM RAW_LAYER.RENTALS r
    ) s
    ON (t.RENTAL_ID = s.RENTAL_ID)
    WHEN MATCHED THEN UPDATE SET
      t.START_DATE_KEY = s.START_DATE_KEY,
      t.END_DATE_KEY   = s.END_DATE_KEY,
      t.BRANCH_ID      = s.BRANCH_ID,
      t.MANAGER_ID     = s.MANAGER_ID,
      t.CAR_ID         = s.CAR_ID,
      t.CUSTOMER_ID    = s.CUSTOMER_ID,
      t.START_AT       = s.START_AT,
      t.DUE_AT         = s.DUE_AT,
      t.RETURN_AT      = s.RETURN_AT,
      t.STATUS         = s.STATUS,
      t.START_ODOMETER = s.START_ODOMETER,
      t.END_ODOMETER   = s.END_ODOMETER,
      t.TOTAL_AMOUNT   = s.TOTAL_AMOUNT,
      t.CURRENCY       = s.CURRENCY,
      t.DURATION_HOURS = s.DURATION_HOURS,
      t.DISTANCE_KM    = s.DISTANCE_KM,
      t.CREATED_AT     = s.CREATED_AT,
      t.LOAD_TS        = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      RENTAL_ID, START_DATE_KEY, END_DATE_KEY, BRANCH_ID, MANAGER_ID, CAR_ID, CUSTOMER_ID,
      START_AT, DUE_AT, RETURN_AT, STATUS, START_ODOMETER, END_ODOMETER,
      TOTAL_AMOUNT, CURRENCY, DURATION_HOURS, DISTANCE_KM, CREATED_AT
    ) VALUES (
      s.RENTAL_ID, s.START_DATE_KEY, s.END_DATE_KEY, s.BRANCH_ID, s.MANAGER_ID, s.CAR_ID, s.CUSTOMER_ID,
      s.START_AT, s.DUE_AT, s.RETURN_AT, s.STATUS, s.START_ODOMETER, s.END_ODOMETER,
      s.TOTAL_AMOUNT, s.CURRENCY, s.DURATION_HOURS, s.DISTANCE_KM, s.CREATED_AT
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_ALERTS IS
  BEGIN
    MERGE INTO FACT_IOT_ALERT t
    USING (
      SELECT
        a.ALERT_ID,
        TO_NUMBER(TO_CHAR(CAST(a.CREATED_AT AS DATE),'YYYYMMDD')) AS DATE_KEY,
        a.BRANCH_ID,
        a.STATUS,
        a.CREATED_AT
      FROM RAW_LAYER.IOT_ALERTS a
    ) s
    ON (t.ALERT_ID = s.ALERT_ID)
    WHEN MATCHED THEN UPDATE SET
      t.DATE_KEY   = s.DATE_KEY,
      t.BRANCH_ID  = s.BRANCH_ID,
      t.STATUS     = s.STATUS,
      t.CREATED_AT = s.CREATED_AT,
      t.LOAD_TS    = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      ALERT_ID, DATE_KEY, BRANCH_ID, STATUS, CREATED_AT
    ) VALUES (
      s.ALERT_ID, s.DATE_KEY, s.BRANCH_ID, s.STATUS, s.CREATED_AT
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_TELEMETRY_DAILY IS
  BEGIN
    MERGE INTO FACT_TELEMETRY_DAILY t
    USING (
      SELECT
        TO_NUMBER(TO_CHAR(CAST(x.EVENT_TS AS DATE),'YYYYMMDD')) AS DATE_KEY,
        c.BRANCH_ID,
        x.CAR_ID,
        x.DEVICE_ID,
        COUNT(*) AS POINTS_CNT,
        AVG(x.SPEED_KMH) AS AVG_SPEED_KMH,
        MAX(x.SPEED_KMH) AS MAX_SPEED_KMH,
        MIN(x.FUEL_LEVEL_PCT) AS MIN_FUEL_PCT,
        MAX(x.FUEL_LEVEL_PCT) KEEP (DENSE_RANK LAST ORDER BY x.EVENT_TS) AS END_FUEL_PCT,
        MAX(x.ENGINE_TEMP_C) AS MAX_ENGINE_TEMP_C,
        SUM(CASE WHEN x.BRAKE_PRESSURE_BAR > 65 THEN 1 ELSE 0 END) AS HARSH_BRAKE_CNT,
        SUM(CASE WHEN x.ACCELERATION_MS2 > 3.5 THEN 1 ELSE 0 END) AS HARSH_ACCEL_CNT,
        SUM(CASE WHEN x.ENGINE_TEMP_C > 110 THEN 1 ELSE 0 END) AS OVERHEAT_CNT
      FROM RAW_LAYER.IOT_TELEMETRY x
      LEFT JOIN RAW_LAYER.CARS c ON c.CAR_ID = x.CAR_ID
      GROUP BY TO_NUMBER(TO_CHAR(CAST(x.EVENT_TS AS DATE),'YYYYMMDD')), c.BRANCH_ID, x.CAR_ID, x.DEVICE_ID
    ) s
    ON (t.DATE_KEY = s.DATE_KEY AND t.CAR_ID = s.CAR_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_ID         = s.BRANCH_ID,
      t.DEVICE_ID         = s.DEVICE_ID,
      t.POINTS_CNT        = s.POINTS_CNT,
      t.AVG_SPEED_KMH     = s.AVG_SPEED_KMH,
      t.MAX_SPEED_KMH     = s.MAX_SPEED_KMH,
      t.MIN_FUEL_PCT      = s.MIN_FUEL_PCT,
      t.END_FUEL_PCT      = s.END_FUEL_PCT,
      t.MAX_ENGINE_TEMP_C = s.MAX_ENGINE_TEMP_C,
      t.HARSH_BRAKE_CNT   = s.HARSH_BRAKE_CNT,
      t.HARSH_ACCEL_CNT   = s.HARSH_ACCEL_CNT,
      t.OVERHEAT_CNT      = s.OVERHEAT_CNT,
      t.LOAD_TS           = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      DATE_KEY, BRANCH_ID, CAR_ID, DEVICE_ID,
      POINTS_CNT, AVG_SPEED_KMH, MAX_SPEED_KMH, MIN_FUEL_PCT, END_FUEL_PCT, MAX_ENGINE_TEMP_C,
      HARSH_BRAKE_CNT, HARSH_ACCEL_CNT, OVERHEAT_CNT
    ) VALUES (
      s.DATE_KEY, s.BRANCH_ID, s.CAR_ID, s.DEVICE_ID,
      s.POINTS_CNT, s.AVG_SPEED_KMH, s.MAX_SPEED_KMH, s.MIN_FUEL_PCT, s.END_FUEL_PCT, s.MAX_ENGINE_TEMP_C,
      s.HARSH_BRAKE_CNT, s.HARSH_ACCEL_CNT, s.OVERHEAT_CNT
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_CAR_SNAP_DAILY IS
  BEGIN
    MERGE INTO FACT_CAR_STATUS_SNAP_DAILY t
    USING (
      SELECT
        TO_NUMBER(TO_CHAR(TRUNC(SYSDATE),'YYYYMMDD')) AS DATE_KEY,
        c.BRANCH_ID,
        c.CAR_ID,
        c.STATUS,
        c.ODOMETER_KM,
        c.DEVICE_ID
      FROM RAW_LAYER.CARS c
    ) s
    ON (t.DATE_KEY = s.DATE_KEY AND t.CAR_ID = s.CAR_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_ID   = s.BRANCH_ID,
      t.STATUS      = s.STATUS,
      t.ODOMETER_KM = s.ODOMETER_KM,
      t.DEVICE_ID   = s.DEVICE_ID,
      t.LOAD_TS     = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      DATE_KEY, BRANCH_ID, CAR_ID, STATUS, ODOMETER_KM, DEVICE_ID
    ) VALUES (
      s.DATE_KEY, s.BRANCH_ID, s.CAR_ID, s.STATUS, s.ODOMETER_KM, s.DEVICE_ID
    );

    COMMIT;
  END;

  PROCEDURE LOAD_ALL IS
  BEGIN
    -- date range large enough for demo
    LOAD_DIM_DATE(TRUNC(SYSDATE) - 365, TRUNC(SYSDATE) + 365);
    LOAD_DIMS;
    LOAD_FACT_RENTAL;
    LOAD_FACT_ALERTS;
    LOAD_FACT_TELEMETRY_DAILY;
    LOAD_FACT_CAR_SNAP_DAILY;
  END;

END PKG_GOLD_LOAD;
/
SHOW ERRORS

PROMPT [OK] Package PKG_GOLD_LOAD created (check SHOW ERRORS output)