-- ======================================================================
-- 5_views_gold.sql — BI-ready wide views
-- ======================================================================
WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
SET SCAN OFF
ALTER SESSION SET CURRENT_SCHEMA = GOLD_LAYER;

CREATE OR REPLACE VIEW VW_GOLD_RENTALS AS
SELECT fr.RENTAL_ID, fr.STATUS, fr.START_AT, fr.DUE_AT, fr.RETURN_AT, fr.DURATION_HOURS, fr.DISTANCE_KM, fr.TOTAL_AMOUNT, fr.CURRENCY, fr.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY, fr.MANAGER_ID, m.MANAGER_CODE, m.FIRST_NAME AS MANAGER_FIRST_NAME, m.LAST_NAME AS MANAGER_LAST_NAME, m.ROLE AS MANAGER_ROLE, fr.CAR_ID, c.LICENSE_PLATE, c.MAKE, c.MODEL, c.MODEL_YEAR, c.COLOR, c.CATEGORY_ID, cat.CATEGORY_NAME, fr.CUSTOMER_ID, cu.FIRST_NAME AS CUSTOMER_FIRST_NAME, cu.LAST_NAME AS CUSTOMER_LAST_NAME, cu.NATIONAL_ID, cu.DRIVER_LICENSE_NO, cu.EMAIL AS CUSTOMER_EMAIL, cu.PHONE AS CUSTOMER_PHONE FROM FACT_RENTAL fr LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = fr.BRANCH_ID LEFT JOIN DIM_MANAGER m ON m.MANAGER_ID = fr.MANAGER_ID LEFT JOIN DIM_CAR c ON c.CAR_ID = fr.CAR_ID LEFT JOIN DIM_CATEGORY cat ON cat.CATEGORY_ID = c.CATEGORY_ID LEFT JOIN DIM_CUSTOMER cu ON cu.CUSTOMER_ID = fr.CUSTOMER_ID;

CREATE OR REPLACE VIEW VW_GOLD_CARS AS
SELECT c.CAR_ID, c.LICENSE_PLATE, c.VIN, c.MAKE, c.MODEL, c.MODEL_YEAR, c.COLOR, c.ODOMETER_KM, c.STATUS, c.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY, c.CATEGORY_ID, cat.CATEGORY_NAME, c.DEVICE_ID, d.DEVICE_CODE, d.STATUS AS DEVICE_STATUS, d.LAST_SEEN_AT FROM DIM_CAR c LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = c.BRANCH_ID LEFT JOIN DIM_CATEGORY cat ON cat.CATEGORY_ID = c.CATEGORY_ID LEFT JOIN DIM_DEVICE d ON d.DEVICE_ID = c.DEVICE_ID;

CREATE OR REPLACE VIEW VW_GOLD_CUSTOMERS AS
SELECT cu.CUSTOMER_ID, cu.FIRST_NAME, cu.LAST_NAME, cu.NATIONAL_ID, cu.DATE_OF_BIRTH, cu.DRIVER_LICENSE_NO, cu.EMAIL, cu.PHONE, cu.CREATED_AT, cu.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY, cu.MANAGER_ID, m.MANAGER_CODE, m.FIRST_NAME AS MANAGER_FIRST_NAME, m.LAST_NAME AS MANAGER_LAST_NAME FROM DIM_CUSTOMER cu LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = cu.BRANCH_ID LEFT JOIN DIM_MANAGER m ON m.MANAGER_ID = cu.MANAGER_ID;

CREATE OR REPLACE VIEW VW_GOLD_DEVICES AS
SELECT d.DEVICE_ID, d.DEVICE_CODE, d.DEVICE_IMEI, d.FIRMWARE_VERSION, d.STATUS, d.ACTIVATED_AT, d.LAST_SEEN_AT, d.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY, c.CAR_ID, c.LICENSE_PLATE, c.MAKE, c.MODEL FROM DIM_DEVICE d LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = d.BRANCH_ID LEFT JOIN DIM_CAR c ON c.DEVICE_ID = d.DEVICE_ID;

CREATE OR REPLACE VIEW VW_GOLD_ALERTS AS
SELECT fa.ALERT_ID, fa.STATUS, fa.CREATED_AT, fa.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY, fa.DATE_KEY FROM FACT_IOT_ALERT fa LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = fa.BRANCH_ID;

COMMIT;
PROMPT [OK] Gold wide views created