-- ======================================================================
-- 6_views_kpi.sql — KPI views for dashboards
-- ======================================================================
WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = GOLD_LAYER;

CREATE OR REPLACE VIEW VW_KPI_RENTALS_DAILY AS
SELECT
  fr.START_DATE_KEY AS DATE_KEY,
  dd.FULL_DATE,
  fr.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  b.BRANCH_NAME,
  COUNT(*) AS RENTALS_CNT,
  SUM(CASE WHEN fr.STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_CNT,
  SUM(CASE WHEN fr.STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_CNT,
  SUM(NVL(fr.TOTAL_AMOUNT,0)) AS REVENUE_TOTAL,
  AVG(NVL(fr.DURATION_HOURS,0)) AS AVG_DURATION_HOURS,
  AVG(NVL(fr.DISTANCE_KM,0)) AS AVG_DISTANCE_KM
FROM FACT_RENTAL fr
LEFT JOIN DIM_DATE dd   ON dd.DATE_KEY  = fr.START_DATE_KEY
LEFT JOIN DIM_BRANCH b  ON b.BRANCH_ID  = fr.BRANCH_ID
GROUP BY fr.START_DATE_KEY, dd.FULL_DATE, fr.BRANCH_ID, b.CITY, b.BRANCH_NAME;

CREATE OR REPLACE VIEW VW_KPI_BRANCH_UTILIZATION_DAILY AS
SELECT
  s.DATE_KEY,
  d.FULL_DATE,
  s.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  b.BRANCH_NAME,
  COUNT(*) AS FLEET_TOTAL,
  SUM(CASE WHEN s.STATUS = 'RENTED' THEN 1 ELSE 0 END) AS RENTED_CNT,
  SUM(CASE WHEN s.STATUS = 'AVAILABLE' THEN 1 ELSE 0 END) AS AVAILABLE_CNT,
  SUM(CASE WHEN s.STATUS = 'MAINTENANCE' THEN 1 ELSE 0 END) AS MAINTENANCE_CNT,
  SUM(CASE WHEN s.STATUS = 'RETIRED' THEN 1 ELSE 0 END) AS RETIRED_CNT
FROM FACT_CAR_STATUS_SNAP_DAILY s
LEFT JOIN DIM_DATE d  ON d.DATE_KEY = s.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY s.DATE_KEY, d.FULL_DATE, s.BRANCH_ID, b.CITY, b.BRANCH_NAME;

CREATE OR REPLACE VIEW VW_KPI_CAR_UTILIZATION_DAILY AS
SELECT
  s.DATE_KEY,
  d.FULL_DATE,
  s.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  s.CAR_ID,
  c.LICENSE_PLATE,
  c.MAKE,
  c.MODEL,
  s.STATUS,
  s.ODOMETER_KM
FROM FACT_CAR_STATUS_SNAP_DAILY s
LEFT JOIN DIM_DATE d ON d.DATE_KEY = s.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = s.BRANCH_ID
LEFT JOIN DIM_CAR c ON c.CAR_ID = s.CAR_ID;

CREATE OR REPLACE VIEW VW_KPI_ALERTS_DAILY AS
SELECT
  fa.DATE_KEY,
  d.FULL_DATE,
  fa.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  COUNT(*) AS ALERTS_TOTAL,
  SUM(CASE WHEN fa.STATUS='OPEN' THEN 1 ELSE 0 END) AS OPEN_CNT,
  SUM(CASE WHEN fa.STATUS='RESOLVED' THEN 1 ELSE 0 END) AS RESOLVED_CNT
FROM FACT_IOT_ALERT fa
LEFT JOIN DIM_DATE d ON d.DATE_KEY = fa.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = fa.BRANCH_ID
GROUP BY fa.DATE_KEY, d.FULL_DATE, fa.BRANCH_ID, b.CITY;

CREATE OR REPLACE VIEW VW_KPI_TELEMETRY_DAILY AS
SELECT
  td.DATE_KEY,
  d.FULL_DATE,
  td.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  td.CAR_ID,
  c.LICENSE_PLATE,
  td.POINTS_CNT,
  td.AVG_SPEED_KMH,
  td.MAX_SPEED_KMH,
  td.MIN_FUEL_PCT,
  td.END_FUEL_PCT,
  td.MAX_ENGINE_TEMP_C,
  td.HARSH_BRAKE_CNT,
  td.HARSH_ACCEL_CNT,
  td.OVERHEAT_CNT
FROM FACT_TELEMETRY_DAILY td
LEFT JOIN DIM_DATE d ON d.DATE_KEY = td.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = td.BRANCH_ID
LEFT JOIN DIM_CAR c ON c.CAR_ID = td.CAR_ID;

CREATE OR REPLACE VIEW VW_KPI_LIVE_CAR_STATUS AS
SELECT
  c.CAR_ID,
  c.LICENSE_PLATE,
  c.MAKE,
  c.MODEL,
  c.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  c.DEVICE_ID,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM RAW_LAYER.RT_IOT_FEED rt
      WHERE rt.CAR_ID = c.CAR_ID
        AND rt.RECEIVED_AT > SYSTIMESTAMP - INTERVAL '2' MINUTE
    ) THEN 1
    ELSE 0
  END AS IS_SENDING_TELEMETRY
FROM DIM_CAR c
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = c.BRANCH_ID;

COMMIT;
PROMPT [OK] KPI views created
