-- ======================================================================
-- gold.sql — GOLD layer (Data Warehouse / OLAP)
-- Schema: GOLD_LAYER
-- Source: SILVER_LAYER (only)
-- Purpose: analytics / KPIs / BI (PowerBI, Tableau)
--
-- Refresh strategy:
-- - GOLD is never critical for app
-- - Async scheduler runs full refresh every 5 minutes (demo-safe default)
-- ======================================================================

WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
SET VERIFY OFF
SET PAGESIZE 200
SET LINESIZE 200

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF3';

ALTER SESSION SET CURRENT_SCHEMA = GOLD_LAYER;

PROMPT [GOLD] Starting deploy...

-- ======================================================================
-- 1) DROP (Idempotent)
-- ======================================================================
BEGIN
  -- Drop scheduler job if exists
  BEGIN
    DBMS_SCHEDULER.DROP_JOB('JOB_GOLD_REFRESH', FORCE => TRUE);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  -- Drop procedure if exists
  BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE GOLD_REFRESH_JOB';
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  -- Drop views first (FULL LIST recreated below)
  FOR v IN (
    SELECT view_name FROM user_views WHERE view_name IN (
      'VW_GOLD_RENTALS','VW_GOLD_CARS','VW_GOLD_CUSTOMERS','VW_GOLD_DEVICES','VW_GOLD_ALERTS',
      'VW_KPI_RENTALS_DAILY','VW_KPI_BRANCH_UTILIZATION_DAILY','VW_KPI_CAR_UTILIZATION_DAILY',
      'VW_KPI_ALERTS_DAILY','VW_KPI_TELEMETRY_DAILY','VW_KPI_LIVE_CAR_STATUS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW '||v.view_name;
  END LOOP;

  -- Drop package
  FOR p IN (
    SELECT object_name FROM user_objects WHERE object_type='PACKAGE' AND object_name='PKG_GOLD_LOAD'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP PACKAGE '||p.object_name;
  END LOOP;

  -- Drop tables
  FOR t IN (
    SELECT table_name FROM user_tables WHERE table_name IN (
      'DIM_DATE','DIM_BRANCH','DIM_MANAGER','DIM_CATEGORY','DIM_CAR','DIM_CUSTOMER','DIM_DEVICE',
      'FACT_RENTAL','FACT_IOT_ALERT','FACT_TELEMETRY_DAILY','FACT_CAR_STATUS_SNAP_DAILY'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/
COMMIT;

PROMPT [GOLD] Drop phase done

-- ======================================================================
-- 2) DIMENSIONS
-- ======================================================================

CREATE TABLE DIM_DATE (
  DATE_KEY        NUMBER(8)    PRIMARY KEY, -- YYYYMMDD
  FULL_DATE       DATE         NOT NULL,
  YEAR_NUM        NUMBER(4)    NOT NULL,
  QUARTER_NUM     NUMBER(1)    NOT NULL,
  MONTH_NUM       NUMBER(2)    NOT NULL,
  MONTH_NAME      VARCHAR2(15) NOT NULL,
  DAY_NUM         NUMBER(2)    NOT NULL,
  DAY_NAME        VARCHAR2(15) NOT NULL,
  WEEK_OF_YEAR    NUMBER(2)    NOT NULL,
  IS_WEEKEND      NUMBER(1)    NOT NULL,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UX_DIM_DATE_FULL ON DIM_DATE(FULL_DATE);

CREATE TABLE DIM_BRANCH (
  BRANCH_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BRANCH_ID    NUMBER NOT NULL,
  BRANCH_NAME  VARCHAR2(100) NOT NULL,
  CITY         VARCHAR2(100) NOT NULL,
  ADDRESS      VARCHAR2(200),
  PHONE        VARCHAR2(30),
  EMAIL        VARCHAR2(100),
  CREATED_AT   TIMESTAMP,
  IS_ACTIVE    NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS      TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_BRANCH ADD CONSTRAINT UK_DIM_BRANCH_NK UNIQUE (BRANCH_ID);
CREATE INDEX IDX_DIM_BRANCH_CITY ON DIM_BRANCH(CITY);

CREATE TABLE DIM_MANAGER (
  MANAGER_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MANAGER_ID    NUMBER NOT NULL,
  MANAGER_CODE  VARCHAR2(20) NOT NULL,
  FIRST_NAME    VARCHAR2(50) NOT NULL,
  LAST_NAME     VARCHAR2(50) NOT NULL,
  EMAIL         VARCHAR2(100) NOT NULL,
  PHONE         VARCHAR2(30),
  ROLE          VARCHAR2(20) NOT NULL,
  BRANCH_ID     NUMBER,
  HIRE_DATE     DATE,
  IS_ACTIVE     NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS       TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_MANAGER ADD CONSTRAINT UK_DIM_MANAGER_NK UNIQUE (MANAGER_ID);
CREATE INDEX IDX_DIM_MANAGER_BRANCH ON DIM_MANAGER(BRANCH_ID);
CREATE INDEX IDX_DIM_MANAGER_ROLE   ON DIM_MANAGER(ROLE);

CREATE TABLE DIM_CATEGORY (
  CATEGORY_KEY   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATEGORY_ID    NUMBER NOT NULL,
  CATEGORY_NAME  VARCHAR2(60) NOT NULL,
  DESCRIPTION    VARCHAR2(400),
  CREATED_AT     TIMESTAMP,
  IS_ACTIVE      NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS        TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_CATEGORY ADD CONSTRAINT UK_DIM_CATEGORY_NK UNIQUE (CATEGORY_ID);
CREATE INDEX IDX_DIM_CATEGORY_NAME ON DIM_CATEGORY(CATEGORY_NAME);

CREATE TABLE DIM_CAR (
  CAR_KEY        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CAR_ID         NUMBER NOT NULL,
  CATEGORY_ID    NUMBER NOT NULL,
  DEVICE_ID      NUMBER,
  VIN            VARCHAR2(30) NOT NULL,
  LICENSE_PLATE  VARCHAR2(20) NOT NULL,
  MAKE           VARCHAR2(60) NOT NULL,
  MODEL          VARCHAR2(60) NOT NULL,
  MODEL_YEAR     NUMBER(4),
  COLOR          VARCHAR2(40),
  IMAGE_URL      VARCHAR2(500),
  ODOMETER_KM    NUMBER(10,0),
  STATUS         VARCHAR2(20),
  BRANCH_ID      NUMBER,
  CREATED_AT     TIMESTAMP,
  IS_ACTIVE      NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS        TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_CAR ADD CONSTRAINT UK_DIM_CAR_NK UNIQUE (CAR_ID);
CREATE INDEX IDX_DIM_CAR_BRANCH ON DIM_CAR(BRANCH_ID);
CREATE INDEX IDX_DIM_CAR_CAT    ON DIM_CAR(CATEGORY_ID);
CREATE INDEX IDX_DIM_CAR_PLATE  ON DIM_CAR(LICENSE_PLATE);

CREATE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID        NUMBER NOT NULL,
  BRANCH_ID          NUMBER NOT NULL,
  MANAGER_ID         NUMBER NOT NULL,
  FIRST_NAME         VARCHAR2(80) NOT NULL,
  LAST_NAME          VARCHAR2(80) NOT NULL,
  NATIONAL_ID        VARCHAR2(20) NOT NULL,
  DATE_OF_BIRTH      DATE NOT NULL,
  DRIVER_LICENSE_NO  VARCHAR2(30) NOT NULL,
  EMAIL              VARCHAR2(160),
  PHONE              VARCHAR2(40),
  CREATED_AT         TIMESTAMP,
  IS_ACTIVE          NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS            TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_CUSTOMER ADD CONSTRAINT UK_DIM_CUSTOMER_NK UNIQUE (CUSTOMER_ID);
CREATE INDEX IDX_DIM_CUSTOMER_BRANCH ON DIM_CUSTOMER(BRANCH_ID);
CREATE INDEX IDX_DIM_CUSTOMER_NAME   ON DIM_CUSTOMER(LAST_NAME, FIRST_NAME);

CREATE TABLE DIM_DEVICE (
  DEVICE_KEY       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DEVICE_ID        NUMBER NOT NULL,
  DEVICE_CODE      VARCHAR2(40) NOT NULL,
  DEVICE_IMEI      VARCHAR2(20),
  FIRMWARE_VERSION VARCHAR2(40),
  STATUS           VARCHAR2(20),
  BRANCH_ID        NUMBER,
  ACTIVATED_AT     TIMESTAMP,
  LAST_SEEN_AT     TIMESTAMP,
  CREATED_AT       TIMESTAMP,
  IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL,
  LOAD_TS          TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE DIM_DEVICE ADD CONSTRAINT UK_DIM_DEVICE_NK UNIQUE (DEVICE_ID);
CREATE INDEX IDX_DIM_DEVICE_BRANCH ON DIM_DEVICE(BRANCH_ID);
CREATE INDEX IDX_DIM_DEVICE_STATUS ON DIM_DEVICE(STATUS);

COMMIT;
PROMPT [GOLD] Dimensions created

-- ======================================================================
-- 3) FACTS
-- ======================================================================

CREATE TABLE FACT_RENTAL (
  RENTAL_KEY       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RENTAL_ID        NUMBER NOT NULL,
  START_DATE_KEY   NUMBER(8) NOT NULL,
  END_DATE_KEY     NUMBER(8),
  BRANCH_ID        NUMBER NOT NULL,
  MANAGER_ID       NUMBER NOT NULL,
  CAR_ID           NUMBER NOT NULL,
  CUSTOMER_ID      NUMBER NOT NULL,
  START_AT         TIMESTAMP NOT NULL,
  DUE_AT           TIMESTAMP NOT NULL,
  RETURN_AT        TIMESTAMP,
  STATUS           VARCHAR2(20),
  START_ODOMETER   NUMBER(10,0),
  END_ODOMETER     NUMBER(10,0),
  TOTAL_AMOUNT     NUMBER(12,2),
  CURRENCY         VARCHAR2(3),
  DURATION_HOURS   NUMBER(10,2),
  DISTANCE_KM      NUMBER(12,2),
  CREATED_AT       TIMESTAMP,
  LOAD_TS          TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE FACT_RENTAL ADD CONSTRAINT UK_FACT_RENTAL_NK UNIQUE (RENTAL_ID);
CREATE INDEX IDX_FACT_RENTAL_STARTKEY ON FACT_RENTAL(START_DATE_KEY);
CREATE INDEX IDX_FACT_RENTAL_BRANCH   ON FACT_RENTAL(BRANCH_ID);
CREATE INDEX IDX_FACT_RENTAL_CAR      ON FACT_RENTAL(CAR_ID);
CREATE INDEX IDX_FACT_RENTAL_MGR      ON FACT_RENTAL(MANAGER_ID);
CREATE INDEX IDX_FACT_RENTAL_STATUS   ON FACT_RENTAL(STATUS);

CREATE TABLE FACT_IOT_ALERT (
  ALERT_KEY    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ALERT_ID     NUMBER NOT NULL,
  DATE_KEY     NUMBER(8) NOT NULL,
  BRANCH_ID    NUMBER,
  CAR_ID       NUMBER,
  RENTAL_ID    NUMBER,
  ALERT_TYPE   VARCHAR2(50),
  SEVERITY     VARCHAR2(10),
  STATUS       VARCHAR2(20),
  EVENT_TS     TIMESTAMP,
  CREATED_AT   TIMESTAMP,
  RESOLVED_AT  TIMESTAMP,
  LOAD_TS      TIMESTAMP DEFAULT SYSTIMESTAMP
);
ALTER TABLE FACT_IOT_ALERT ADD CONSTRAINT UK_FACT_ALERT_NK UNIQUE (ALERT_ID);
CREATE INDEX IDX_FACT_ALERT_DATE   ON FACT_IOT_ALERT(DATE_KEY);
CREATE INDEX IDX_FACT_ALERT_BRANCH ON FACT_IOT_ALERT(BRANCH_ID);
CREATE INDEX IDX_FACT_ALERT_STATUS ON FACT_IOT_ALERT(STATUS);

CREATE TABLE FACT_TELEMETRY_DAILY (
  TELEMETRY_DAY_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATE_KEY          NUMBER(8) NOT NULL,
  BRANCH_ID         NUMBER,
  CAR_ID            NUMBER NOT NULL,
  DEVICE_ID         NUMBER,
  POINTS_CNT        NUMBER,
  AVG_SPEED_KMH     NUMBER(10,2),
  MAX_SPEED_KMH     NUMBER(10,2),
  MIN_FUEL_PCT      NUMBER(10,2),
  END_FUEL_PCT      NUMBER(10,2),
  MAX_ENGINE_TEMP_C NUMBER(10,2),
  HARSH_BRAKE_CNT   NUMBER,
  HARSH_ACCEL_CNT   NUMBER,
  OVERHEAT_CNT      NUMBER,
  LOAD_TS           TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UX_FACT_TELEM_DAILY ON FACT_TELEMETRY_DAILY(DATE_KEY, CAR_ID);
CREATE INDEX IDX_FACT_TELEM_BRANCH     ON FACT_TELEMETRY_DAILY(BRANCH_ID);

CREATE TABLE FACT_CAR_STATUS_SNAP_DAILY (
  SNAP_KEY     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATE_KEY     NUMBER(8) NOT NULL,
  BRANCH_ID    NUMBER,
  CAR_ID       NUMBER NOT NULL,
  STATUS       VARCHAR2(20),
  ODOMETER_KM  NUMBER(10,0),
  DEVICE_ID    NUMBER,
  LOAD_TS      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UX_FACT_CAR_SNAP ON FACT_CAR_STATUS_SNAP_DAILY(DATE_KEY, CAR_ID);
CREATE INDEX IDX_FACT_CAR_SNAP_BRANCH ON FACT_CAR_STATUS_SNAP_DAILY(BRANCH_ID);
CREATE INDEX IDX_FACT_CAR_SNAP_STATUS ON FACT_CAR_STATUS_SNAP_DAILY(STATUS);

COMMIT;
PROMPT [GOLD] Facts created

-- ======================================================================
-- 4) LOAD PACKAGE (ELT from SILVER)
-- ======================================================================

CREATE OR REPLACE PACKAGE PKG_GOLD_LOAD AS
  PROCEDURE LOAD_DIM_DATE(p_start_date DATE, p_end_date DATE);
  PROCEDURE LOAD_DIMS;
  PROCEDURE LOAD_FACT_RENTAL;
  PROCEDURE LOAD_FACT_ALERTS;
  PROCEDURE LOAD_FACT_TELEMETRY_DAILY;
  PROCEDURE LOAD_FACT_CAR_SNAP_DAILY;
  PROCEDURE LOAD_ALL;
END PKG_GOLD_LOAD;
/
SHOW ERRORS

CREATE OR REPLACE PACKAGE BODY PKG_GOLD_LOAD AS

  PROCEDURE LOAD_DIM_DATE(p_start_date DATE, p_end_date DATE) IS
    d DATE := TRUNC(p_start_date);
  BEGIN
    WHILE d <= TRUNC(p_end_date) LOOP
      MERGE INTO DIM_DATE t
      USING (
        SELECT
          TO_NUMBER(TO_CHAR(d,'YYYYMMDD')) AS DATE_KEY,
          d AS FULL_DATE,
          TO_NUMBER(TO_CHAR(d,'YYYY')) AS YEAR_NUM,
          TO_NUMBER(TO_CHAR(d,'Q')) AS QUARTER_NUM,
          TO_NUMBER(TO_CHAR(d,'MM')) AS MONTH_NUM,
          TRIM(TO_CHAR(d,'Month')) AS MONTH_NAME,
          TO_NUMBER(TO_CHAR(d,'DD')) AS DAY_NUM,
          TRIM(TO_CHAR(d,'Day')) AS DAY_NAME,
          TO_NUMBER(TO_CHAR(d,'IW')) AS WEEK_OF_YEAR,
          CASE WHEN TO_CHAR(d,'DY','NLS_DATE_LANGUAGE=ENGLISH') IN ('SAT','SUN') THEN 1 ELSE 0 END AS IS_WEEKEND
        FROM dual
      ) s
      ON (t.DATE_KEY = s.DATE_KEY)
      WHEN MATCHED THEN UPDATE SET
        t.FULL_DATE    = s.FULL_DATE,
        t.YEAR_NUM     = s.YEAR_NUM,
        t.QUARTER_NUM  = s.QUARTER_NUM,
        t.MONTH_NUM    = s.MONTH_NUM,
        t.MONTH_NAME   = s.MONTH_NAME,
        t.DAY_NUM      = s.DAY_NUM,
        t.DAY_NAME     = s.DAY_NAME,
        t.WEEK_OF_YEAR = s.WEEK_OF_YEAR,
        t.IS_WEEKEND   = s.IS_WEEKEND
      WHEN NOT MATCHED THEN INSERT (
        DATE_KEY, FULL_DATE, YEAR_NUM, QUARTER_NUM, MONTH_NUM, MONTH_NAME,
        DAY_NUM, DAY_NAME, WEEK_OF_YEAR, IS_WEEKEND
      ) VALUES (
        s.DATE_KEY, s.FULL_DATE, s.YEAR_NUM, s.QUARTER_NUM, s.MONTH_NUM, s.MONTH_NAME,
        s.DAY_NUM, s.DAY_NAME, s.WEEK_OF_YEAR, s.IS_WEEKEND
      );
      d := d + 1;
    END LOOP;
    COMMIT;
  END;

  PROCEDURE LOAD_DIMS IS
  BEGIN
    MERGE INTO DIM_BRANCH t
    USING (SELECT BRANCH_ID, BRANCH_NAME, CITY, ADDRESS, PHONE, EMAIL, CREATED_AT FROM SILVER_LAYER.BRANCHES) s
    ON (t.BRANCH_ID = s.BRANCH_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_NAME = s.BRANCH_NAME, t.CITY=s.CITY, t.ADDRESS=s.ADDRESS, t.PHONE=s.PHONE, t.EMAIL=s.EMAIL,
      t.CREATED_AT=s.CREATED_AT, t.IS_ACTIVE=1, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (BRANCH_ID, BRANCH_NAME, CITY, ADDRESS, PHONE, EMAIL, CREATED_AT, IS_ACTIVE)
    VALUES (s.BRANCH_ID, s.BRANCH_NAME, s.CITY, s.ADDRESS, s.PHONE, s.EMAIL, s.CREATED_AT, 1);

    MERGE INTO DIM_MANAGER t
    USING (SELECT MANAGER_ID, MANAGER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ROLE, BRANCH_ID, HIRE_DATE FROM SILVER_LAYER.MANAGERS) s
    ON (t.MANAGER_ID = s.MANAGER_ID)
    WHEN MATCHED THEN UPDATE SET
      t.MANAGER_CODE=s.MANAGER_CODE, t.FIRST_NAME=s.FIRST_NAME, t.LAST_NAME=s.LAST_NAME, t.EMAIL=s.EMAIL,
      t.PHONE=s.PHONE, t.ROLE=s.ROLE, t.BRANCH_ID=s.BRANCH_ID, t.HIRE_DATE=s.HIRE_DATE, t.IS_ACTIVE=1, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (MANAGER_ID, MANAGER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ROLE, BRANCH_ID, HIRE_DATE, IS_ACTIVE)
    VALUES (s.MANAGER_ID, s.MANAGER_CODE, s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PHONE, s.ROLE, s.BRANCH_ID, s.HIRE_DATE, 1);

    MERGE INTO DIM_CATEGORY t
    USING (SELECT CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, CREATED_AT FROM SILVER_LAYER.CAR_CATEGORIES) s
    ON (t.CATEGORY_ID = s.CATEGORY_ID)
    WHEN MATCHED THEN UPDATE SET
      t.CATEGORY_NAME=s.CATEGORY_NAME, t.DESCRIPTION=s.DESCRIPTION, t.CREATED_AT=s.CREATED_AT, t.IS_ACTIVE=1, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, CREATED_AT, IS_ACTIVE)
    VALUES (s.CATEGORY_ID, s.CATEGORY_NAME, s.DESCRIPTION, s.CREATED_AT, 1);

    MERGE INTO DIM_CAR t
    USING (
      SELECT CAR_ID, CATEGORY_ID, DEVICE_ID, VIN, LICENSE_PLATE, MAKE, MODEL, MODEL_YEAR, COLOR, IMAGE_URL,
             ODOMETER_KM, STATUS, BRANCH_ID, CREATED_AT
      FROM SILVER_LAYER.CARS
    ) s
    ON (t.CAR_ID = s.CAR_ID)
    WHEN MATCHED THEN UPDATE SET
      t.CATEGORY_ID=s.CATEGORY_ID, t.DEVICE_ID=s.DEVICE_ID, t.VIN=s.VIN, t.LICENSE_PLATE=s.LICENSE_PLATE,
      t.MAKE=s.MAKE, t.MODEL=s.MODEL, t.MODEL_YEAR=s.MODEL_YEAR, t.COLOR=s.COLOR, t.IMAGE_URL=s.IMAGE_URL,
      t.ODOMETER_KM=s.ODOMETER_KM, t.STATUS=s.STATUS, t.BRANCH_ID=s.BRANCH_ID, t.CREATED_AT=s.CREATED_AT,
      t.IS_ACTIVE=1, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      CAR_ID, CATEGORY_ID, DEVICE_ID, VIN, LICENSE_PLATE, MAKE, MODEL, MODEL_YEAR, COLOR, IMAGE_URL,
      ODOMETER_KM, STATUS, BRANCH_ID, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.CAR_ID, s.CATEGORY_ID, s.DEVICE_ID, s.VIN, s.LICENSE_PLATE, s.MAKE, s.MODEL, s.MODEL_YEAR, s.COLOR, s.IMAGE_URL,
      s.ODOMETER_KM, s.STATUS, s.BRANCH_ID, s.CREATED_AT, 1
    );

    MERGE INTO DIM_CUSTOMER t
    USING (
      SELECT CUSTOMER_ID, BRANCH_ID, MANAGER_ID, FIRST_NAME, LAST_NAME, NATIONAL_ID, DATE_OF_BIRTH,
             DRIVER_LICENSE_NO, EMAIL, PHONE, CREATED_AT
      FROM SILVER_LAYER.CUSTOMERS
    ) s
    ON (t.CUSTOMER_ID = s.CUSTOMER_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_ID=s.BRANCH_ID, t.MANAGER_ID=s.MANAGER_ID, t.FIRST_NAME=s.FIRST_NAME, t.LAST_NAME=s.LAST_NAME,
      t.NATIONAL_ID=s.NATIONAL_ID, t.DATE_OF_BIRTH=s.DATE_OF_BIRTH, t.DRIVER_LICENSE_NO=s.DRIVER_LICENSE_NO,
      t.EMAIL=s.EMAIL, t.PHONE=s.PHONE, t.CREATED_AT=s.CREATED_AT, t.IS_ACTIVE=1, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      CUSTOMER_ID, BRANCH_ID, MANAGER_ID, FIRST_NAME, LAST_NAME, NATIONAL_ID, DATE_OF_BIRTH,
      DRIVER_LICENSE_NO, EMAIL, PHONE, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.CUSTOMER_ID, s.BRANCH_ID, s.MANAGER_ID, s.FIRST_NAME, s.LAST_NAME, s.NATIONAL_ID, s.DATE_OF_BIRTH,
      s.DRIVER_LICENSE_NO, s.EMAIL, s.PHONE, s.CREATED_AT, 1
    );

    MERGE INTO DIM_DEVICE t
    USING (
      SELECT DEVICE_ID, DEVICE_CODE, DEVICE_IMEI, FIRMWARE_VERSION, STATUS, BRANCH_ID, ACTIVATED_AT, LAST_SEEN_AT, CREATED_AT
      FROM SILVER_LAYER.IOT_DEVICES
    ) s
    ON (t.DEVICE_ID = s.DEVICE_ID)
    WHEN MATCHED THEN UPDATE SET
      t.DEVICE_CODE=s.DEVICE_CODE, t.DEVICE_IMEI=s.DEVICE_IMEI, t.FIRMWARE_VERSION=s.FIRMWARE_VERSION,
      t.STATUS=s.STATUS, t.BRANCH_ID=s.BRANCH_ID, t.ACTIVATED_AT=s.ACTIVATED_AT, t.LAST_SEEN_AT=s.LAST_SEEN_AT,
      t.CREATED_AT=s.CREATED_AT, t.IS_ACTIVE=1, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      DEVICE_ID, DEVICE_CODE, DEVICE_IMEI, FIRMWARE_VERSION, STATUS, BRANCH_ID,
      ACTIVATED_AT, LAST_SEEN_AT, CREATED_AT, IS_ACTIVE
    ) VALUES (
      s.DEVICE_ID, s.DEVICE_CODE, s.DEVICE_IMEI, s.FIRMWARE_VERSION, s.STATUS, s.BRANCH_ID,
      s.ACTIVATED_AT, s.LAST_SEEN_AT, s.CREATED_AT, 1
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_RENTAL IS
  BEGIN
    MERGE INTO FACT_RENTAL t
    USING (
      SELECT
        r.RENTAL_ID,
        TO_NUMBER(TO_CHAR(CAST(r.START_AT AS DATE),'YYYYMMDD')) AS START_DATE_KEY,
        TO_NUMBER(TO_CHAR(CAST(NVL(r.RETURN_AT, r.DUE_AT) AS DATE),'YYYYMMDD')) AS END_DATE_KEY,
        r.BRANCH_ID, r.MANAGER_ID, r.CAR_ID, r.CUSTOMER_ID,
        r.START_AT, r.DUE_AT, r.RETURN_AT, r.STATUS,
        r.START_ODOMETER, r.END_ODOMETER,
        r.TOTAL_AMOUNT, r.CURRENCY,
        ROUND(
          (CAST(NVL(r.RETURN_AT, r.DUE_AT) AS DATE) - CAST(r.START_AT AS DATE)) * 24,
          2
        ) AS DURATION_HOURS,
        CASE WHEN r.START_ODOMETER IS NOT NULL AND r.END_ODOMETER IS NOT NULL
             THEN ROUND(r.END_ODOMETER - r.START_ODOMETER, 2)
             ELSE NULL END AS DISTANCE_KM,
        r.CREATED_AT
      FROM SILVER_LAYER.RENTALS r
    ) s
    ON (t.RENTAL_ID = s.RENTAL_ID)
    WHEN MATCHED THEN UPDATE SET
      t.START_DATE_KEY=s.START_DATE_KEY, t.END_DATE_KEY=s.END_DATE_KEY,
      t.BRANCH_ID=s.BRANCH_ID, t.MANAGER_ID=s.MANAGER_ID, t.CAR_ID=s.CAR_ID, t.CUSTOMER_ID=s.CUSTOMER_ID,
      t.START_AT=s.START_AT, t.DUE_AT=s.DUE_AT, t.RETURN_AT=s.RETURN_AT, t.STATUS=s.STATUS,
      t.START_ODOMETER=s.START_ODOMETER, t.END_ODOMETER=s.END_ODOMETER,
      t.TOTAL_AMOUNT=s.TOTAL_AMOUNT, t.CURRENCY=s.CURRENCY,
      t.DURATION_HOURS=s.DURATION_HOURS, t.DISTANCE_KM=s.DISTANCE_KM,
      t.CREATED_AT=s.CREATED_AT, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      RENTAL_ID, START_DATE_KEY, END_DATE_KEY, BRANCH_ID, MANAGER_ID, CAR_ID, CUSTOMER_ID,
      START_AT, DUE_AT, RETURN_AT, STATUS, START_ODOMETER, END_ODOMETER,
      TOTAL_AMOUNT, CURRENCY, DURATION_HOURS, DISTANCE_KM, CREATED_AT
    ) VALUES (
      s.RENTAL_ID, s.START_DATE_KEY, s.END_DATE_KEY, s.BRANCH_ID, s.MANAGER_ID, s.CAR_ID, s.CUSTOMER_ID,
      s.START_AT, s.DUE_AT, s.RETURN_AT, s.STATUS, s.START_ODOMETER, s.END_ODOMETER,
      s.TOTAL_AMOUNT, s.CURRENCY, s.DURATION_HOURS, s.DISTANCE_KM, s.CREATED_AT
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_ALERTS IS
  BEGIN
    MERGE INTO FACT_IOT_ALERT t
    USING (
      SELECT
        a.ALERT_ID,
        TO_NUMBER(TO_CHAR(CAST(a.CREATED_AT AS DATE),'YYYYMMDD')) AS DATE_KEY,
        a.BRANCH_ID,
        a.CAR_ID,
        a.RENTAL_ID,
        a.ALERT_TYPE,
        a.SEVERITY,
        a.STATUS,
        a.EVENT_TS,
        a.CREATED_AT,
        a.RESOLVED_AT
      FROM SILVER_LAYER.IOT_ALERTS a
    ) s
    ON (t.ALERT_ID = s.ALERT_ID)
    WHEN MATCHED THEN UPDATE SET
      t.DATE_KEY=s.DATE_KEY, t.BRANCH_ID=s.BRANCH_ID, t.CAR_ID=s.CAR_ID, t.RENTAL_ID=s.RENTAL_ID,
      t.ALERT_TYPE=s.ALERT_TYPE, t.SEVERITY=s.SEVERITY, t.STATUS=s.STATUS,
      t.EVENT_TS=s.EVENT_TS, t.CREATED_AT=s.CREATED_AT, t.RESOLVED_AT=s.RESOLVED_AT,
      t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      ALERT_ID, DATE_KEY, BRANCH_ID, CAR_ID, RENTAL_ID, ALERT_TYPE, SEVERITY, STATUS, EVENT_TS, CREATED_AT, RESOLVED_AT
    ) VALUES (
      s.ALERT_ID, s.DATE_KEY, s.BRANCH_ID, s.CAR_ID, s.RENTAL_ID, s.ALERT_TYPE, s.SEVERITY, s.STATUS, s.EVENT_TS, s.CREATED_AT, s.RESOLVED_AT
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_TELEMETRY_DAILY IS
  BEGIN
    MERGE INTO FACT_TELEMETRY_DAILY t
    USING (
      SELECT
        TO_NUMBER(TO_CHAR(CAST(x.EVENT_TS AS DATE),'YYYYMMDD')) AS DATE_KEY,
        c.BRANCH_ID,
        x.CAR_ID,
        x.DEVICE_ID,
        COUNT(*) AS POINTS_CNT,
        AVG(x.SPEED_KMH) AS AVG_SPEED_KMH,
        MAX(x.SPEED_KMH) AS MAX_SPEED_KMH,
        MIN(x.FUEL_LEVEL_PCT) AS MIN_FUEL_PCT,
        MAX(x.FUEL_LEVEL_PCT) KEEP (DENSE_RANK LAST ORDER BY x.EVENT_TS) AS END_FUEL_PCT,
        MAX(x.ENGINE_TEMP_C) AS MAX_ENGINE_TEMP_C,
        SUM(CASE WHEN x.BRAKE_PRESSURE_BAR > 65 THEN 1 ELSE 0 END) AS HARSH_BRAKE_CNT,
        SUM(CASE WHEN x.ACCELERATION_MS2 > 3.5 THEN 1 ELSE 0 END) AS HARSH_ACCEL_CNT,
        SUM(CASE WHEN x.ENGINE_TEMP_C > 110 THEN 1 ELSE 0 END) AS OVERHEAT_CNT
      FROM SILVER_LAYER.IOT_TELEMETRY x
      LEFT JOIN SILVER_LAYER.CARS c ON c.CAR_ID = x.CAR_ID
      GROUP BY TO_NUMBER(TO_CHAR(CAST(x.EVENT_TS AS DATE),'YYYYMMDD')), c.BRANCH_ID, x.CAR_ID, x.DEVICE_ID
    ) s
    ON (t.DATE_KEY = s.DATE_KEY AND t.CAR_ID = s.CAR_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_ID=s.BRANCH_ID, t.DEVICE_ID=s.DEVICE_ID,
      t.POINTS_CNT=s.POINTS_CNT, t.AVG_SPEED_KMH=s.AVG_SPEED_KMH, t.MAX_SPEED_KMH=s.MAX_SPEED_KMH,
      t.MIN_FUEL_PCT=s.MIN_FUEL_PCT, t.END_FUEL_PCT=s.END_FUEL_PCT, t.MAX_ENGINE_TEMP_C=s.MAX_ENGINE_TEMP_C,
      t.HARSH_BRAKE_CNT=s.HARSH_BRAKE_CNT, t.HARSH_ACCEL_CNT=s.HARSH_ACCEL_CNT, t.OVERHEAT_CNT=s.OVERHEAT_CNT,
      t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (
      DATE_KEY, BRANCH_ID, CAR_ID, DEVICE_ID,
      POINTS_CNT, AVG_SPEED_KMH, MAX_SPEED_KMH, MIN_FUEL_PCT, END_FUEL_PCT, MAX_ENGINE_TEMP_C,
      HARSH_BRAKE_CNT, HARSH_ACCEL_CNT, OVERHEAT_CNT
    ) VALUES (
      s.DATE_KEY, s.BRANCH_ID, s.CAR_ID, s.DEVICE_ID,
      s.POINTS_CNT, s.AVG_SPEED_KMH, s.MAX_SPEED_KMH, s.MIN_FUEL_PCT, s.END_FUEL_PCT, s.MAX_ENGINE_TEMP_C,
      s.HARSH_BRAKE_CNT, s.HARSH_ACCEL_CNT, s.OVERHEAT_CNT
    );

    COMMIT;
  END;

  PROCEDURE LOAD_FACT_CAR_SNAP_DAILY IS
  BEGIN
    MERGE INTO FACT_CAR_STATUS_SNAP_DAILY t
    USING (
      SELECT
        TO_NUMBER(TO_CHAR(TRUNC(SYSDATE),'YYYYMMDD')) AS DATE_KEY,
        c.BRANCH_ID, c.CAR_ID, c.STATUS, c.ODOMETER_KM, c.DEVICE_ID
      FROM SILVER_LAYER.CARS c
    ) s
    ON (t.DATE_KEY = s.DATE_KEY AND t.CAR_ID = s.CAR_ID)
    WHEN MATCHED THEN UPDATE SET
      t.BRANCH_ID=s.BRANCH_ID, t.STATUS=s.STATUS, t.ODOMETER_KM=s.ODOMETER_KM, t.DEVICE_ID=s.DEVICE_ID, t.LOAD_TS=SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (DATE_KEY, BRANCH_ID, CAR_ID, STATUS, ODOMETER_KM, DEVICE_ID)
    VALUES (s.DATE_KEY, s.BRANCH_ID, s.CAR_ID, s.STATUS, s.ODOMETER_KM, s.DEVICE_ID);

    COMMIT;
  END;

  PROCEDURE LOAD_ALL IS
  BEGIN
    LOAD_DIM_DATE(TRUNC(SYSDATE) - 365, TRUNC(SYSDATE) + 365);
    LOAD_DIMS;
    LOAD_FACT_RENTAL;
    LOAD_FACT_ALERTS;
    LOAD_FACT_TELEMETRY_DAILY;
    LOAD_FACT_CAR_SNAP_DAILY;
  END;

END PKG_GOLD_LOAD;
/
SHOW ERRORS





PROMPT [GOLD] Package created

-- ======================================================================
-- 5) BI-READY VIEWS (FULL SET, consistent with drop list)
-- ======================================================================

CREATE OR REPLACE VIEW VW_GOLD_RENTALS AS
SELECT
  fr.RENTAL_ID, fr.STATUS, fr.START_AT, fr.DUE_AT, fr.RETURN_AT, fr.DURATION_HOURS, fr.DISTANCE_KM,
  fr.TOTAL_AMOUNT, fr.CURRENCY, fr.BRANCH_ID,
  b.BRANCH_NAME, b.CITY AS BRANCH_CITY,
  fr.MANAGER_ID, m.MANAGER_CODE, m.FIRST_NAME AS MANAGER_FIRST_NAME, m.LAST_NAME AS MANAGER_LAST_NAME, m.ROLE AS MANAGER_ROLE,
  fr.CAR_ID, c.LICENSE_PLATE, c.MAKE, c.MODEL, c.MODEL_YEAR, c.COLOR, c.CATEGORY_ID, cat.CATEGORY_NAME,
  fr.CUSTOMER_ID, cu.FIRST_NAME AS CUSTOMER_FIRST_NAME, cu.LAST_NAME AS CUSTOMER_LAST_NAME, cu.NATIONAL_ID,
  cu.DRIVER_LICENSE_NO, cu.EMAIL AS CUSTOMER_EMAIL, cu.PHONE AS CUSTOMER_PHONE
FROM FACT_RENTAL fr
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = fr.BRANCH_ID
LEFT JOIN DIM_MANAGER m ON m.MANAGER_ID = fr.MANAGER_ID
LEFT JOIN DIM_CAR c ON c.CAR_ID = fr.CAR_ID
LEFT JOIN DIM_CATEGORY cat ON cat.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN DIM_CUSTOMER cu ON cu.CUSTOMER_ID = fr.CUSTOMER_ID;

CREATE OR REPLACE VIEW VW_GOLD_CARS AS
SELECT
  c.CAR_ID, c.LICENSE_PLATE, c.VIN, c.MAKE, c.MODEL, c.MODEL_YEAR, c.COLOR, c.ODOMETER_KM, c.STATUS,
  c.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY,
  c.CATEGORY_ID, cat.CATEGORY_NAME,
  c.DEVICE_ID, d.DEVICE_CODE, d.STATUS AS DEVICE_STATUS, d.LAST_SEEN_AT
FROM DIM_CAR c
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = c.BRANCH_ID
LEFT JOIN DIM_CATEGORY cat ON cat.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN DIM_DEVICE d ON d.DEVICE_ID = c.DEVICE_ID;

CREATE OR REPLACE VIEW VW_GOLD_CUSTOMERS AS
SELECT
  cu.CUSTOMER_ID, cu.FIRST_NAME, cu.LAST_NAME, cu.NATIONAL_ID, cu.DATE_OF_BIRTH, cu.DRIVER_LICENSE_NO,
  cu.EMAIL, cu.PHONE, cu.CREATED_AT, cu.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY,
  cu.MANAGER_ID, m.MANAGER_CODE, m.FIRST_NAME AS MANAGER_FIRST_NAME, m.LAST_NAME AS MANAGER_LAST_NAME
FROM DIM_CUSTOMER cu
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = cu.BRANCH_ID
LEFT JOIN DIM_MANAGER m ON m.MANAGER_ID = cu.MANAGER_ID;

CREATE OR REPLACE VIEW VW_GOLD_DEVICES AS
SELECT
  d.DEVICE_ID, d.DEVICE_CODE, d.DEVICE_IMEI, d.FIRMWARE_VERSION, d.STATUS, d.ACTIVATED_AT, d.LAST_SEEN_AT,
  d.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY,
  c.CAR_ID, c.LICENSE_PLATE, c.MAKE, c.MODEL
FROM DIM_DEVICE d
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = d.BRANCH_ID
LEFT JOIN DIM_CAR c ON c.DEVICE_ID = d.DEVICE_ID;

CREATE OR REPLACE VIEW VW_GOLD_ALERTS AS
SELECT
  fa.ALERT_ID, fa.STATUS, fa.ALERT_TYPE, fa.SEVERITY,
  fa.EVENT_TS, fa.CREATED_AT, fa.RESOLVED_AT,
  fa.BRANCH_ID, b.BRANCH_NAME, b.CITY AS BRANCH_CITY,
  fa.CAR_ID, fa.RENTAL_ID,
  fa.DATE_KEY
FROM FACT_IOT_ALERT fa
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = fa.BRANCH_ID;

-- KPI: Rentals daily
CREATE OR REPLACE VIEW VW_KPI_RENTALS_DAILY AS
SELECT
  fr.START_DATE_KEY AS DATE_KEY,
  dd.FULL_DATE,
  fr.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  b.BRANCH_NAME,
  COUNT(*) AS RENTALS_CNT,
  SUM(CASE WHEN fr.STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_CNT,
  SUM(CASE WHEN fr.STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_CNT,
  SUM(NVL(fr.TOTAL_AMOUNT,0)) AS REVENUE_TOTAL,
  AVG(NVL(fr.DURATION_HOURS,0)) AS AVG_DURATION_HOURS,
  AVG(NVL(fr.DISTANCE_KM,0)) AS AVG_DISTANCE_KM
FROM FACT_RENTAL fr
LEFT JOIN DIM_DATE dd   ON dd.DATE_KEY  = fr.START_DATE_KEY
LEFT JOIN DIM_BRANCH b  ON b.BRANCH_ID  = fr.BRANCH_ID
GROUP BY fr.START_DATE_KEY, dd.FULL_DATE, fr.BRANCH_ID, b.CITY, b.BRANCH_NAME;

-- KPI: Branch utilization daily (snapshot)
CREATE OR REPLACE VIEW VW_KPI_BRANCH_UTILIZATION_DAILY AS
SELECT
  s.DATE_KEY,
  d.FULL_DATE,
  s.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  b.BRANCH_NAME,
  COUNT(*) AS FLEET_TOTAL,
  SUM(CASE WHEN s.STATUS = 'RENTED' THEN 1 ELSE 0 END) AS RENTED_CNT,
  SUM(CASE WHEN s.STATUS = 'AVAILABLE' THEN 1 ELSE 0 END) AS AVAILABLE_CNT,
  SUM(CASE WHEN s.STATUS = 'MAINTENANCE' THEN 1 ELSE 0 END) AS MAINTENANCE_CNT,
  SUM(CASE WHEN s.STATUS = 'RETIRED' THEN 1 ELSE 0 END) AS RETIRED_CNT
FROM FACT_CAR_STATUS_SNAP_DAILY s
LEFT JOIN DIM_DATE d  ON d.DATE_KEY = s.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY s.DATE_KEY, d.FULL_DATE, s.BRANCH_ID, b.CITY, b.BRANCH_NAME;

-- KPI: Car utilization daily (per car snapshot)
CREATE OR REPLACE VIEW VW_KPI_CAR_UTILIZATION_DAILY AS
SELECT
  s.DATE_KEY,
  d.FULL_DATE,
  s.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  s.CAR_ID,
  c.LICENSE_PLATE,
  c.MAKE,
  c.MODEL,
  s.STATUS,
  s.ODOMETER_KM
FROM FACT_CAR_STATUS_SNAP_DAILY s
LEFT JOIN DIM_DATE d ON d.DATE_KEY = s.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = s.BRANCH_ID
LEFT JOIN DIM_CAR c ON c.CAR_ID = s.CAR_ID;

-- KPI: Alerts daily
CREATE OR REPLACE VIEW VW_KPI_ALERTS_DAILY AS
SELECT
  fa.DATE_KEY,
  d.FULL_DATE,
  fa.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  COUNT(*) AS ALERTS_TOTAL,
  SUM(CASE WHEN fa.STATUS='OPEN' THEN 1 ELSE 0 END) AS OPEN_CNT,
  SUM(CASE WHEN fa.STATUS='RESOLVED' THEN 1 ELSE 0 END) AS RESOLVED_CNT
FROM FACT_IOT_ALERT fa
LEFT JOIN DIM_DATE d ON d.DATE_KEY = fa.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = fa.BRANCH_ID
GROUP BY fa.DATE_KEY, d.FULL_DATE, fa.BRANCH_ID, b.CITY;

-- KPI: Telemetry daily (from history table aggregation in facts)
CREATE OR REPLACE VIEW VW_KPI_TELEMETRY_DAILY AS
SELECT
  td.DATE_KEY,
  d.FULL_DATE,
  td.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  td.CAR_ID,
  c.LICENSE_PLATE,
  td.POINTS_CNT,
  td.AVG_SPEED_KMH,
  td.MAX_SPEED_KMH,
  td.MIN_FUEL_PCT,
  td.END_FUEL_PCT,
  td.MAX_ENGINE_TEMP_C,
  td.HARSH_BRAKE_CNT,
  td.HARSH_ACCEL_CNT,
  td.OVERHEAT_CNT
FROM FACT_TELEMETRY_DAILY td
LEFT JOIN DIM_DATE d ON d.DATE_KEY = td.DATE_KEY
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = td.BRANCH_ID
LEFT JOIN DIM_CAR c ON c.CAR_ID = td.CAR_ID;

-- KPI: Live car status (reads SILVER RT feed)
CREATE OR REPLACE VIEW VW_KPI_LIVE_CAR_STATUS AS
SELECT
  c.CAR_ID,
  c.LICENSE_PLATE,
  c.MAKE,
  c.MODEL,
  c.BRANCH_ID,
  b.CITY AS BRANCH_CITY,
  c.DEVICE_ID,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM SILVER_LAYER.RT_IOT_FEED rt
      WHERE rt.CAR_ID = c.CAR_ID
        AND rt.RECEIVED_AT > SYSTIMESTAMP - INTERVAL '2' MINUTE
    ) THEN 1 ELSE 0
  END AS IS_SENDING_TELEMETRY
FROM DIM_CAR c
LEFT JOIN DIM_BRANCH b ON b.BRANCH_ID = c.BRANCH_ID;

COMMIT;
PROMPT [GOLD] Views created

-- ======================================================================
-- 6) Scheduler (async refresh)
-- Runs full refresh every 5 minutes (demo-safe)
-- ======================================================================

CREATE OR REPLACE PROCEDURE GOLD_REFRESH_JOB AS
BEGIN
  GOLD_LAYER.PKG_GOLD_LOAD.LOAD_ALL;
END;
/
SHOW ERRORS

BEGIN
  BEGIN
    DBMS_SCHEDULER.DROP_JOB('JOB_GOLD_REFRESH', FORCE => TRUE);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  DBMS_SCHEDULER.CREATE_JOB (
    job_name        => 'JOB_GOLD_REFRESH',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN GOLD_LAYER.GOLD_REFRESH_JOB; END;',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=MINUTELY;INTERVAL=5',
    enabled         => TRUE,
    comments        => 'Async refresh GOLD from SILVER (dims + facts + snapshots)'
  );
END;
/
PROMPT [OK] JOB_GOLD_REFRESH enabled (every 5 minutes)
PROMPT [OK] GOLD deployed
